version: '3.5'

services:
  # nginx:
  #   build: ./requirements/nginx
  #   container_name: nginx
  #   image: nginx:inception
  #   ports:
  #     - '443:443'
  #   env_file:
  #     - .env
  #   restart: always
  #   networks:
  #     - nat

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:inception
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    networks:
      - nat

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   image: wordpress:inception
  #   ports:
  #     - '9000:9000'
  #   env_file:
  #     - .env
  #   restart: always
  #   networks:
  #     - nat

networks:
  nat:
    driver: bridge
